---
- name: Zabbix Event Processing
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: Test AAP Job Execution
      condition: event.payload.message == "Hello"
      action:
        run_job_template:
          name: "Power On Proxmox VM"
          organization: "Default"
